[
{ "cc_library": {
    "name": "test",
    "cc_headers": [ "test.h" ],
    "dependencies": [ "//common/third_party/google/googletest:googletest" ]
} },
{ "cc_library": {
    "name": "test_main",
    "cc_headers": [ "test.h" ],
    "dependencies": [ "//common/third_party/google/googletest:googletest_main" ]
} }
]