[
{ "cc_library": {
    "name": "test",
    "cc_headers": [ "test.h" ],
    "dependencies": [ "//common/third_party/google/googletest:googletest",
                      "//common/base:tcmalloc_perf"
     ]
} },

{ "cc_library": {
    "name": "test_main",
    "cc_headers": [ "test.h" ],
    "dependencies": [ "//common/third_party/google/googletest:googletest_main",
                      "//common/base:tcmalloc_perf"
     ]
} },

{ "cc_library": {
    "name": "test_no_heapcheck",
    "cc_headers": [ "test.h" ],
    "dependencies": [ "//common/third_party/google/googletest:googletest" ]
} },

{ "cc_library": {
    "name": "test_main_no_heapcheck",
    "cc_headers": [ "test.h" ],
    "dependencies": [ "//common/third_party/google/googletest:googletest_main" ]
} }
]