[
 { "cc_binary": {
     "name" : "strutil_test",
     "cc_sources": [ "strutil_test.cc" ],
     "dependencies": [ "//common/base:base",
                       "//common/strings:strutil" ]
   }
 },
 { "cc_binary": {
     "name" : "path_test",
     "cc_sources": [ "path_test.cc" ],
     "dependencies": [ "//common/base:base",
                       "//common/strings:strutil" ]
   }
 }
]