[
{ "cc_library": {
    "name": "threadpool",
    "cc_sources": [ "threadpool.cc" ],
    "cc_headers": [ "threadpool.h" ],
    "dependencies": [ "//common/base:callback",
                      "//common/log:log"
     ]
} },
{ "cc_library": {
    "name": "counter",
    "cc_headers": [ "counter.h" ],
    "dependencies": [ "//common/base:macros",
                      "//common/log:log"
     ]
} }
]