[
 { "cc_library": {
     "name" : "shell",
     "cc_sources" : [ "shell.cc" ],
     "cc_headers" : [ "shell.h" ]
   }
 },
 { "cc_library": {
     "name" : "stl",
     "cc_headers" : [ "stl.h" ],
     "depenencies": [ "//common/base:callback" ]
   }
 }
]