[
 { "cc_library": {
     "name" : "stringpiece",
     "dependencies": [ "//common/third_party/google/re2:re2" ]
   }
 },
 { "cc_library": {
     "name" : "strutil",
     "cc_sources" : [ "strutil.cc", "path.cc", "varmap.cc" ],
     "cc_headers" : [ "strutil.h", "path.h", "varmap.h" ],
     "dependencies": [ ":stringpiece" ]
   }
 }
]