[
 { "cc_library": {
     "name" : "fileutil",
     "cc_sources" : [ "fileutil.cc" ],
     "cc_headers" : [ "fileutil.h" ],
     "dependencies": [ "//common/log:log" ]
   }
 },
 { "cc_library": {
     "name" : "linereader",
     "cc_sources" : [ "linereader.cc" ],
     "cc_headers" : [ "linereader.h" ],
     "dependencies": [ "//common/log:log" ]
   }
 }
]