 [
 { "cc_library": {
     "name" : "init",
     "cc_sources": [ "init.cc" ],
     "cc_headers" : [ "init.h" ]
   }
 },
 { "cc_library": {
     "name" : "time",
     "cc_sources" : [ "time.cc" ],
     "cc_headers" : [ "time.h", "rdtsc.h" ]
   }
 },
 { "cc_library": {
     "name" : "types",
     "cc_headers" : [ "types.h" ]
   }
 },
 { "cc_library": {
     "name" : "base",
     "dependencies": [ ":init", ":time", ":types" ]
   }
 }
]