[
 { "cc_test": {
     "name": "callback_test",
     "cc_sources": [ "callback_test.cc" ],
     "dependencies": [ "//common/base:callback",
                       "//common/test:test_main"
      ]
  } }
]